#Aqui precisa especificar de onde virão as Gems
#O comando bundler install instala as gems que foram escritas nesse arquivo.

source 'https://rubygems.org'
gem 'cpf_utils', '1.3.0'
gem 'faker'
gem 'lerolero_generator'